# Generated by Django 5.0.1 on 2026-09-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='descircao',
            new_name='descricao',
        ),
    ]
