# Generated by Django 5.0.1 on 2026-09-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achados', '0002_rename_descircao_categoria_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objeto',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='local',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('DEVOLVIDO', 'Devolvido')], default='PENDENTE', max_length=10),
        ),
    ]
