# Generated by Django 5.0.1 on 2026-09-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achados', '0003_remove_objeto_tipo_alter_categoria_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='devolvido_para',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='objeto',
            name='matricula_recebedor',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
