# Generated by Django 5.0.1 on 2026-03-23 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Deletado em')),
                ('is_active', models.BooleanField(default=True, editable=False, verbose_name='Está ativo?')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('session_key', models.CharField(blank=True, max_length=50, null=True, verbose_name='Session key')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='user-agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('path', models.TextField(blank=True, null=True, verbose_name='Path')),
            ],
            options={
                'verbose_name': 'Tentativa de login',
                'verbose_name_plural': 'Tentativas de login',
                'ordering': ('-timestamp',),
                'abstract': False,
            },
        ),
    ]
