# Generated by Django 5.0.1 on 2026-03-23 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Deletado em')),
                ('is_active', models.BooleanField(default=True, editable=False, verbose_name='Está ativo?')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PUBLISHED', 'Publicado'), ('ARCHIVED', 'Arquivado')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicado em')),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Deletado em')),
                ('is_active', models.BooleanField(default=True, editable=False, verbose_name='Está ativo?')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Deletado em')),
                ('is_active', models.BooleanField(default=True, editable=False, verbose_name='Está ativo?')),
                ('title', models.CharField(help_text='Título do documento', max_length=255, verbose_name='Título')),
                ('content', models.TextField(blank=True, help_text='Conteúdo do documento', null=True, verbose_name='Conteúdo')),
                ('file', models.FileField(blank=True, help_text='Arquivo anexo do documento', null=True, upload_to='documents/%Y/%m/', verbose_name='Arquivo')),
                ('category', models.CharField(choices=[('POLICY', 'Política'), ('PROCEDURE', 'Procedimento'), ('MANUAL', 'Manual'), ('OTHER', 'Outro')], default='OTHER', max_length=50, verbose_name='Categoria')),
                ('is_published', models.BooleanField(default=False, help_text='Define se o documento está publicado', verbose_name='Publicado')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Deletado em')),
                ('is_active', models.BooleanField(default=True, editable=False, verbose_name='Está ativo?')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('color', models.CharField(default='#007bff', help_text='Cor em hexadecimal (ex: #007bff)', max_length=7, verbose_name='Cor')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
